### PR TITLE
Changed all instances in code of Hydroshare Author to xDCIShare Author.

### PR DESCRIPTION
**Pull request by cbcunc**

### CODE REVIEW

**Comment by mjstealey** [comment]
@cbcunc - I'm thinking that somewhere down the line the custom group "**XXXshare Author**" where **XXX** is whatever brand of site is being stood up is going to bite us sooner or later. Thinking that some kind of generic term like "**Resource Author**" or similar could better serve the purpose, never need to be renamed again, and is easier to document.

Adding @hyi for her opinion as well.

**Comment by cbcunc** [comment]
Agree. Will change it again in another issue/PR.

**Comment by cbcunc** [comment]
All this marge did was make it work. Will fix it to something better long term soon.

**Comment by mjstealey** [comment]
> Agree. Will change it again in another issue/PR.

Perfect 👍

**Comment by hyi** [comment]
@mjstealey Totally agreed on changing "XXXShare Author" to a generic term like "Resource Author." In fact, if we remove dependency on Mezzanine, we may not need this Author group at all. @cbcunc

**Comment by cbcunc** [comment]
Suggestion implemented in #35.

**Pull request merged**
